#!/usr/bin/env python3
"""Fetch per-post page views from GA4 Data API and write src/data/post-views.json.

Uses the OAuth token cached by `scripts/google_api_auth_test.py`
(`~/.config/wport_blog/google_oauth_token.json`).

Aggregates `screenPageViews` by `pagePath` restricted to `/blog/posts/*`,
then extracts the slug (`/blog/posts/<slug>[/[index.html]]`).

Usage:
    python3 scripts/fetch_ga4_views.py [--property 514959680] [--since 2024-01-01]

Exit codes:
    0 success (may still be zero rows if no traffic yet)
    1 no OAuth token / refresh failed
    2 GA4 API returned non-200
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

TOKEN_PATH = Path.home() / ".config/wport_blog/google_oauth_token.json"
DEFAULT_PROPERTY_ID = "514959680"
BLOG_PATH_PREFIX = "/blog/posts/"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src/data/post-views.json"

SLUG_PATTERN = re.compile(
    r"^/blog/posts/(?P<slug>[^/?#]+?)(?:\.html|/index\.html|/)?(?:[?#].*)?$"
)


def load_token() -> str:
    try:
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
    except ImportError as exc:
        raise SystemExit(
            "Missing dependencies. Install with: pip3 install google-auth google-auth-httplib2 google-auth-oauthlib"
        ) from exc

    if not TOKEN_PATH.exists():
        print(f"OAuth token not found at {TOKEN_PATH}", file=sys.stderr)
        print("Run scripts/google_api_auth_test.py once to authorise.", file=sys.stderr)
        raise SystemExit(1)

    creds = Credentials.from_authorized_user_file(str(TOKEN_PATH))
    if not creds.valid:
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            TOKEN_PATH.write_text(creds.to_json(), encoding="utf-8")
        else:
            print(
                "Token invalid and no refresh token available. Re-run google_api_auth_test.py.",
                file=sys.stderr,
            )
            raise SystemExit(1)

    return creds.token


def run_report(property_id: str, token: str, start_date: str) -> dict:
    body = {
        "dateRanges": [{"startDate": start_date, "endDate": "today"}],
        "dimensions": [{"name": "pagePath"}],
        "metrics": [{"name": "screenPageViews"}],
        "dimensionFilter": {
            "filter": {
                "fieldName": "pagePath",
                "stringFilter": {
                    "matchType": "BEGINS_WITH",
                    "value": BLOG_PATH_PREFIX,
                },
            }
        },
        "limit": 100000,
    }
    url = f"https://analyticsdata.googleapis.com/v1beta/properties/{property_id}:runReport"
    request = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as error:
        body = error.read().decode()
        print(f"GA4 API HTTP {error.code}: {body[:500]}", file=sys.stderr)
        raise SystemExit(2) from error


def parse_slug(page_path: str) -> str | None:
    match = SLUG_PATTERN.match(page_path)
    if not match:
        return None
    slug = match.group("slug").strip()
    return slug or None


def aggregate_views(report: dict) -> dict[str, int]:
    views: dict[str, int] = {}
    for row in report.get("rows", []):
        dimension_values = row.get("dimensionValues", [])
        metric_values = row.get("metricValues", [])
        if not dimension_values or not metric_values:
            continue

        page_path = dimension_values[0].get("value", "")
        raw = metric_values[0].get("value", "0")
        try:
            count = int(raw)
        except ValueError:
            continue

        slug = parse_slug(page_path)
        if not slug:
            continue

        views[slug] = views.get(slug, 0) + count
    return views


def write_output(views: dict[str, int]) -> None:
    payload = {
        "_meta": {
            "note": "auto-generated by scripts/fetch_ga4_views.py; do not edit manually",
            "updatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        },
        "views": dict(sorted(views.items())),
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--property",
        default=DEFAULT_PROPERTY_ID,
        help=f"GA4 property numeric ID (default: {DEFAULT_PROPERTY_ID})",
    )
    parser.add_argument(
        "--since",
        default="2024-01-01",
        help="Start date (YYYY-MM-DD). Default 2024-01-01 for lifetime-like totals.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print aggregated views to stdout without writing the JSON file.",
    )
    args = parser.parse_args()

    token = load_token()
    report = run_report(args.property, token, args.since)
    views = aggregate_views(report)

    if args.dry_run:
        print(json.dumps(views, ensure_ascii=False, indent=2))
        return 0

    write_output(views)
    total = sum(views.values())
    print(f"Wrote {len(views)} posts, {total} total views -> {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
